## 1 задача
1. Скачать данные по ссылке https://www.kaggle.com/datasets/ionaskel/laptop-prices
2. Считать данные с помощью pandas
3. Вывести на экран первые 5 строк

In [11]:
import pandas as pd

df = pd.read_csv('laptops.csv', sep=';')
df.head()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

### 1.1 Создать новый признак Cpu_Company, который будет содержать только название фирмы, которая произвела CPU

In [13]:
df['Cpu_Company'] = df['Cpu'].apply(lambda x: x.split(' ')[0])
df.head()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel

In [15]:
df['Cpu_Company'].value_counts()

Cpu_Company
Intel      1240
AMD          62
Samsung       1
Name: count, dtype: int64

### 1.2 Создать новый признак Memory_Amount, который будет содержать только количество Gb памяти без указания типа носителя

In [18]:
df['Memory'].value_counts()

Memory
256GB SSD                        412
1TB HDD                          223
500GB HDD                        132
512GB SSD                        118
128GB SSD +  1TB HDD              94
128GB SSD                         76
256GB SSD +  1TB HDD              73
32GB Flash Storage                38
2TB HDD                           16
64GB Flash Storage                15
512GB SSD +  1TB HDD              14
1TB SSD                           14
256GB SSD +  2TB HDD              10
1.0TB Hybrid                       9
256GB Flash Storage                8
16GB Flash Storage                 7
32GB SSD                           6
180GB SSD                          5
128GB Flash Storage                4
512GB SSD +  2TB HDD               3
16GB SSD                           3
512GB Flash Storage                2
1TB SSD +  1TB HDD                 2
256GB SSD +  500GB HDD             2
128GB SSD +  2TB HDD               2
256GB SSD +  256GB SSD             2
512GB SSD +  256GB SSD             1
512GB SSD +  512GB SSD             1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
32GB HDD                           1
64GB SSD                           1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

In [20]:
def convert_to_gb(x):
    memory = x.split(' ')[0]
    if memory.endswith('GB'):
        res = memory.replace('GB', '')
    elif memory.endswith('TB'):
        res = float(memory.replace('TB', '')) * 1024
    return int(res)

df['Memory_Amount'] = df['Memory'].apply(convert_to_gb)
df.head()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256

In [22]:
df['Memory_Amount'].value_counts()

Memory_Amount
256     508
1024    250
128     177
512     140
500     132
32       45
64       17
2048     16
16       10
180       5
240       1
8         1
508       1
Name: count, dtype: int64

### 1.3 Создать новый признак Memory_Type, который будет содержать только тип носителя (HDD/SDD/др.)

In [35]:
def Type(x):
    if '+' in x:
        mem1 = x.split('B')[1][:x.split('B')[1].find('+')].strip() # strip() - удаление пробелов
        mem2 = x.split('B')[-1].strip()
        res = mem1 + ' ' + mem2
    else:
        res = x.split('B')[-1].strip()
    return res

df['Memory_Type'] = df['Memory'].apply(Type)
df.head()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash Storage
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD

In [33]:
df['Memory_Type'].value_counts()

Memory_Type
SSD                  637
HDD                  374
SSD HDD              200
Flash Storage         74
Hybrid                10
SSD SSD                4
SSD Hybrid             2
Flash Storage HDD      1
HDD HDD                1
Name: count, dtype: int64

### 1.4 Удалите признаки Memory и ScreenResolution

In [40]:
df.drop(columns=['Memory', 'ScreenResolution'], inplace=True)
df.head()

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD
1,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash Storage
2,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD
3,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD
4,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD

## 2 Задача

### 2.1 Создайте признак SSD, который изначально равен 0

In [45]:
df['SSD'] = 0
df.head()

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD,0
1,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash Storage,0
2,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD,0
3,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD,0
4,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD,0

### 2.2 Поставьте в признаке SSD 1, если ноутбук действительно с типом носителя SSD

In [49]:
df.loc[df['Memory_Type'] == 'SSD', 'SSD'] = 1
df.head()

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD,1
1,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash Storage,0
2,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD,1
3,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD,1
4,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD,1

### 2.3 Уберите в признаке Weight значения 'kg' и поменяйте его тип данных на вещественный

In [57]:
df['Weight'] = df['Weight'].str.replace('kg', '').astype('float')

AttributeError: Can only use .str accessor with string values!

In [59]:
df.head()

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128,SSD,1
1,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,898.94,Intel,128,Flash Storage,0
2,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86,575.00,Intel,256,SSD,1
3,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83,2537.45,Intel,512,SSD,1
4,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,Intel,256,SSD,1

## 3 Задача

Создайте датафрейм с клиентами:
```
clients = pd.DataFrame({
'client_id': [45, 32, 67, 33, 43],
'laptop_id': [506, 398, 710, 120, 1999]
})
```

In [65]:
clients = pd.DataFrame({
'client_id': [45, 32, 67, 33, 43],
'laptop_id': [506, 398, 710, 120, 1999]
})

In [67]:
clients

   client_id  laptop_id
0         45        506
1         32        398
2         67        710
3         33        120
4         43       1999

### 3.1 Присоедините к таблице clients данные по ноутбукам через метод join
Это нужно, чтобы понимать, какие ноутбуки покупались клиентами

laptop_id - это индексы датафрейма с ноутбуками

In [70]:
clients_lap_id = clients.set_index('laptop_id')
clients_lap_id

           client_id
laptop_id
506               45
398               32
710               67
120               33
1999              43

In [72]:
joined = clients_lap_id.join(df)
joined

,client_id,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
laptop_id,,,,,,,,,,,,,,,
506,45,Asus,ZenBook UX510UX-CN211T,Notebook,15.6,Intel Core i7 7500U 2.7GHz,8GB,Intel HD Graphics 620,Windows 10,2.00,1224.0,Intel,256.0,SSD HDD,0.0
398,32,Dell,Precision M5520,Workstation,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia Quadro M1200,Windows 10,1.78,2712.0,Intel,256.0,SSD,1.0
710,67,Lenovo,Legion Y520-15IKBN,Gaming,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.50,1249.0,Intel,128.0,SSD HDD,0.0
120,33,Acer,Spin 3,Notebook,15.6,Intel Core i3 7100U 2.4GHz,6GB,Intel HD Graphics 620,Windows 10,2.10,479.0,Intel,1024.0,HDD,0.0
1999,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 3.2 Присоедините к таблице clients данные по ноутбукам через метод merge
Это нужно, чтобы понимать, какие ноутбуки покупались клиентами

laptop_id - это индексы датафрейма с ноутбуками

In [76]:
df['Laptop_id'] = df.index
df.head()

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD,Laptop_id
0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128,SSD,1,0
1,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,898.94,Intel,128,Flash Storage,0,1
2,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86,575.00,Intel,256,SSD,1,2
3,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83,2537.45,Intel,512,SSD,1,3
4,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,Intel,256,SSD,1,4

In [80]:
merged = clients.merge(df, left_on='laptop_id', right_on='Laptop_id') # on=''
merged

,client_id,laptop_id,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD,Laptop_id
0,45,506,Asus,ZenBook UX510UX-CN211T,Notebook,15.6,Intel Core i7 7500U 2.7GHz,8GB,Intel HD Graphics 620,Windows 10,2.00,1224.0,Intel,256,SSD HDD,0,506
1,32,398,Dell,Precision M5520,Workstation,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia Quadro M1200,Windows 10,1.78,2712.0,Intel,256,SSD,1,398
2,67,710,Lenovo,Legion Y520-15IKBN,Gaming,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.50,1249.0,Intel,128,SSD HDD,0,710
3,33,120,Acer,Spin 3,Notebook,15.6,Intel Core i3 7100U 2.4GHz,6GB,Intel HD Graphics 620,Windows 10,2.10,479.0,Intel,1024,HDD,0,120

## 4 Задача
Составьте несколько сводных таблиц

### 4.1 Найдите среднюю стоимость ноутбуков в зависимости от компании производителя
Отсортируйте от меньшей стоимости к большей

In [85]:
df.groupby('Company').agg({'Price_euros' : 'mean'}).sort_values('Price_euros')

           Price_euros
Company
Vero        217.425000
Mediacom    295.000000
Chuwi       314.296667
Acer        626.775825
Fujitsu     729.000000
HP         1067.774854
Lenovo     1086.384444
Asus       1104.169367
Xiaomi     1133.462500
Dell       1186.068990
Toshiba    1267.812500
Samsung    1413.444444
Huawei     1424.000000
Apple      1564.198571
Microsoft  1612.308333
Google     1677.666667
MSI        1728.908148
LG         2099.000000
Razer      3346.142857

### 4.2 Найдите минимальную, среднюю и максимальную стоимости ноутбуков в зависимости от производителя процессора

In [91]:
df.groupby('Cpu_Company').agg({'Price_euros' : ['min', 'mean', 'max']}) # .fillna(0)

            Price_euros
                    min         mean     max
Cpu_Company
AMD               199.0   560.638871  2199.0
Intel             174.0  1152.214145  6099.0
Samsung           659.0   659.000000   659.0

### 4.3 Постройте таблицу с подсчетом количества ноутбуков в данных в зависимости от производителя CPU и ОЗУ

In [98]:
df.pivot_table(index=['Cpu_Company'], columns='Ram', aggfunc='count', values='Weight', fill_value=0)

Ram          12GB  16GB  24GB  2GB  32GB  4GB  64GB  6GB  8GB
Cpu_Company
AMD             2     3     0    1     0   31     0   13   12
Intel          23   197     3   21    17  343     1   28  607
Samsung         0     0     0    0     0    1     0    0    0

### 4.4 Постройте таблицу с подсчетом средней стоимости ноутбуков в данных в зависимости от операционной системы и GB памяти

In [102]:
df.pivot_table(index='OpSys', columns='Memory_Amount', aggfunc='mean', values='Price_euros', fill_value=0)

Memory_Amount,8,16,32,64,128,180,240,256,500,508,512,1024,2048
OpSys,,,,,,,,,,,,,
Android,0.0,0.00,0.000000,434.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0000
Chrome OS,0.0,305.38,412.454545,774.333333,1275.000000,0.0,0.0,1559.000000,0.000000,0.0,2199.000000,0.000000,0.0000
Linux,0.0,0.00,0.000000,0.000000,742.250000,0.0,0.0,811.638125,389.056364,0.0,0.000000,581.401290,0.0000
Mac OS X,0.0,0.00,0.000000,0.000000,1099.000000,0.0,0.0,1311.994000,0.000000,0.0,1222.000000,0.000000,0.0000
No OS,0.0,0.00,0.000000,0.000000,562.140000,0.0,0.0,782.989286,404.675385,0.0,1098.500000,540.539600,594.0000
Windows 10,2249.0,0.00,270.001471,499.716000,1026.489167,1073.5,3100.0,1334.456872,664.717647,0.0,1911.985285,904.827906,666.9475
Windows 10 S,0.0,0.00,0.000000,308.995000,1039.000000,0.0,0.0,1668.950000,0.000000,0.0,2589.000000,0.000000,0.0000
Windows 7,0.0,0.00,0.000000,0.000000,1320.323333,1199.0,0.0,1846.466800,924.048333,1002.0,2235.396667,1539.666667,0.0000
macOS,0.0,0.00,0.000000,0.000000,1119.315000,0.0,0.0,1600.370000,0.000000,0.0,2180.870000,0.000000,0.0000

## 5 Задача*
Ответьте на несколько вопросов

### 5.1 Ноутбуков каких компаний и с каким процессором больше?

In [109]:
pd.crosstab(index=df['Company'], columns=df['Cpu_Company'])

Cpu_Company  AMD  Intel  Samsung
Company
Acer          10     93        0
Apple          0     21        0
Asus          11    147        0
Chuwi          0      3        0
Dell           0    297        0
Fujitsu        0      3        0
Google         0      3        0
HP            25    249        0
Huawei         0      2        0
LG             0      3        0
Lenovo        16    281        0
MSI            0     54        0
Mediacom       0      7        0
Microsoft      0      6        0
Razer          0      7        0
Samsung        0      8        1
Toshiba        0     48        0
Vero           0      4        0
Xiaomi         0      4        0

### 5.2 С каким типом памяти и с каким объемом памяти больше ноутбуков?

In [114]:
pd.crosstab(index=df['Memory_Type'], columns=df['Memory_Amount'])

Memory_Amount,8,16,32,64,128,180,240,256,500,508,512,1024,2048
Memory_Type,,,,,,,,,,,,,
Flash Storage,0,7,38,15,4,0,0,8,0,0,2,0,0
Flash Storage HDD,0,0,0,1,0,0,0,0,0,0,0,0,0
HDD,0,0,1,0,1,0,0,0,132,0,0,224,16
HDD HDD,0,0,0,0,0,0,0,0,0,0,0,1,0
Hybrid,0,0,0,0,0,0,0,0,0,1,0,9,0
SSD,1,3,6,1,76,5,1,412,0,0,118,14,0
SSD HDD,0,0,0,0,96,0,0,85,0,0,17,2,0
SSD Hybrid,0,0,0,0,0,0,0,1,0,0,1,0,0
SSD SSD,0,0,0,0,0,0,0,2,0,0,2,0,0

In [117]:
df.to_excel(r'C:\Users\danii\Desktop\GeekBrains\Python for DA\1.xlsx') # Сохранение датасета на комп

In [119]:
df.to_excel('1.xlsx') # Сохранение датасета в облачное хранилище